marketplace/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

marketplace/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

from . import views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

marketplace/marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # set homepage to index view
    path('', include('core.urls')),

    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/conversation/models.py
from django.contrib.auth.models import User
from django.db import models

from item.models import Item

class Conversation(models.Model):
    item = models.ForeignKey(Item, related_name='conversations', on_delete=models.CASCADE)
    members = models.ManyToManyField(User, related_name='conversations')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-modified_at']

class ConversationMessage(models.Model):
    conversation = models.ForeignKey(Conversation, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    created_by = models.ForeignKey(User, related_name='messages', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

marketplace/conversation/forms.py
from django import forms

from .models import ConversationMessage

class ConversationMessageForm(forms.ModelForm):
    class Meta:
        model = ConversationMessage
        fields = ('content', )
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
                }),
        }

marketplace/conversation/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from item.models import Item
from .models import Conversation
from .forms import ConversationMessageForm

@login_required
def new_conversation(request, item_pk):
    item = get_object_or_404(Item, pk=item_pk)

    if item.created_by == request.user:
        return redirect('dashboard:index')

    conversations = Conversation.objects.filter(item=item).filter(members__in=[request.user.id])

    if conversations:
        pass # redirect to existing conversation

    if request.method == 'POST':
        form = ConversationMessageForm(request.POST)

        if form.is_valid():
            conversation = Conversation.objects.create(item=item)
            conversation.members.add(request.user)
            conversation.members.add(item.created_by)
            conversation.save()

            conversation_message = form.save(commit=False)
            conversation_message.conversation = conversation
            conversation_message.created_by = request.user
            conversation_message.save()

            return redirect('item:detail', pk=item_pk)
    else:
        form = ConversationMessageForm()

    return render(request, 'conversation/new.html', {
        'form': form,
        'item': item,
    })

@login_required
def inbox(request):
    conversations = Conversation.objects.filter(members__in=[request.user.id])

    return render(request, 'conversation/inbox.html', {
        'conversations': conversations,
    })

@login_required
def detail(request, pk):
    conversation = Conversation.objects.filter(members__in=[request.user.id]).get(pk=pk)

    return render(request, 'conversation/detail.html', {
        'conversation': conversation,
    })

marketplace/conversation/templates/conversation/detail.html
{% extends 'core/base.html' %}

{% block title %}Conversation{% endblock %}
{% block content %}
    <h1 class="mb-6 text-3xl">Conversation</h1>

    <img src="{{ conversation.item.image.url }}" alt="" class="rounded-xl w-20">
  <div class="space-y-6">
    {% for message in conversation.messages.all %}
          <div class="p-6 flex bg-gray-100 rounded-xl">
            <div>
              <p class="mb-4"><strong>{{ message.created_by.username }} </strong> @ {{ message.created_at }} </p>
              <p class="mb-4">{{ message.content }}</p>
            </div>
          </div>
    {% endfor %}
  </div>

{% endblock %}

marketplace/conversation/templates/conversation/inbox.html
{% extends 'core/base.html' %}

{% block title %}Inbox{% endblock %}
{% block content %}
    <h1 class="mb-6 text-3xl">Inbox</h1>

  <div class="space-y-6">
    {% for conversation in conversations %}
      <a href="{% url 'conversation:detail' conversation.id %}" >
          <div class="p-6 flex bg-gray-100 rounded-xl">
            <div class="pr-6">
              <img src="{{ conversation.item.image.url }}" alt="" class="rounded-xl w-20">
            </div>
            <div>
              {% for member in conversation.members.all %}
                {% if member != request.user %}
                  <p class="mb-4"><strong>{{ member.username }}</strong> | {{ conversation.modified_at }}</p>
                  <p> {{ conversation.item.name }}</p>
                  {% endif %}
              {% endfor %}
      </a>
    {% endfor %}
  </div>

{% endblock %}

marketplace/conversation/templates/conversation/new.html
{% extends 'core/base.html' %}

{% block title %}New conversation{% endblock %}
{% block content %}
    <h1 class="mb-6 text-3xl">New conversation</h1>

    <form method="post" action='.'>
        {% csrf_token %}

        <div class="space-y-4">
        {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                  {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}



        <button type="submit"class="text-white mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl">  Send</button>
    </form>

{% endblock %}